[build]
# the folder where Hugo builds the site and Netlify will serve
publish = "public/"
# the build command
command = "hugo --gc --minify"

[build.environment]
HUGO_BASE_URL = "https://cpsc.johnhollowell.com/"
