blank_issues_enabled: false
contact_links:
  - name: Maintenance Request
    url: https://github.com/jhollowe/cpsc/pulls
    about: Create a Pull Request for a small error like a typo or a broken link
